Actualización de modelo de db para uso de cuenta bancaria
udistrital/giros_crud pull request #16
Opened 2021-11-12 20:45 UTC by diagutierrezro

udistrital/tesoreria_cliente/issues/25

2021-11-13 02:00 UTC, AlexFBP requested changes
En general bien
- un ajuste menor y quedaría
- Por favor, colocar también en la carpeta `database` el .dbm de pgmodeler

2021-11-17 23:16 UTC, diagutierrezro commented on database/scripts/giros_update_cuenta_bancaria_up.sql
> +ADD COLUMN divisa_id integer NOT NULL;
Se realiza el ajuste y se agrega el .dbm

2021-11-18 03:01 UTC, AlexFBP requested changes
Adicional a lo comentado, actualizar el README para que tenga links a los modelos SVG y PGmodeler. Como referencia:
https://github.com/udistrital/movimientos_crud/blob/a1a6737f19ec00b7da1a0607bb28c249d7dbed0e/README.md?plain=1#L78-L82

2021-11-18 15:50 UTC, diagutierrezro commented on database/scripts/giros_update_cuenta_bancaria_up.sql
> +ADD COLUMN divisa_id integer NOT NULL;
- Agrego comentarios a las columnas 
![image](https://user-images.githubusercontent.com/38676533/142448933-73bb2610-3e33-4298-a314-f7ddae5aa549.png)
- Se modifican los nombres del up y down y se ajusta el archivo .go

2021-11-18 16:54 UTC, diagutierrezro commented on database/scripts/giros_update_cuenta_bancaria_down.sql
> +END $$;
- Al separar los pasos en diferentes partes (`DO ... END`) se obtiene error de que no se pueden insertar multiples ordenes en una sentencia preparada por lo que se deja como está
![image](https://user-images.githubusercontent.com/38676533/142460449-4852e9a9-dce3-4140-bd22-f8b53ded7ec1.png)
- Se renombra el archivo y se ajusta el .go

2021-11-18 17:36 UTC, AlexFBP approved these changes

2021-11-18 17:36 UTC, merged