Se modifica el modelo para actualizacion de cuentas bancarias
udistrital/giros_crud pull request #20
Opened 2021-11-24 01:34 UTC by diagutierrezro

udistrital/tesoreria_cliente/25

2021-11-25 01:41 UTC, AlexFBP requested changes

2021-11-25 01:41 UTC, AlexFBP commented on controllers/cuenta_bancaria.go
>  		v.FechaModificacion = time_bogota.TiempoBogotaFormato()
Mover el `v.FechaModificacion = ...` también al models/cuenta_bancaria.go

2021-11-25 15:49 UTC, diagutierrezro commented on controllers/cuenta_bancaria.go
>  		v.FechaModificacion = time_bogota.TiempoBogotaFormato()
Se modifica la fechaModificacion en el modelo y se eliminan del controlador

2021-11-26 01:40 UTC, AlexFBP approved these changes

2021-11-26 01:40 UTC, merged